[deps]
BiophysicalBehaviour = "17159459-d6a3-4a3d-a4c5-9872d9e70704"
BiophysicalGeometry = "06c61620-4f66-4020-a018-07befe374221"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
ConstructionBase = "187b0558-2788-49d3-abe0-74a17ed4e7c9"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
FluidProperties = "d16f1b92-71d3-42f3-aafa-43e5bb0efda8"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
HeatExchange = "720bd838-cdd6-4aad-926b-452b962dce21"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Microclimate = "fa5d2a79-de00-40ba-a9f4-ff140fbe07ba"
ModelParameters = "4744a3fa-6c31-4707-899e-a3298e4618ad"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SolarRadiation = "d01e3663-6acb-4162-92ee-c50acb918cac"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
